// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineCoursess.Context;

#nullable disable

namespace OnlineCoursess.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20251116212500_AddContentTitles")]
    partial class AddContentTitles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineCourses.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Programming"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Design"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Business"
                        });
                });

            modelBuilder.Entity("OnlineCourses.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Build a complete web application using ASP.NET MVC and Entity Framework.",
                            Duration = 20,
                            InstructorId = 1,
                            Level = "Intermediate",
                            Price = 49.99m,
                            Title = "ASP.NET MVC Web Development"
                        },
                        new
                        {
                            CourseId = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Master modern design principles and prototyping for mobile and web.",
                            Duration = 15,
                            InstructorId = 2,
                            Level = "Advanced",
                            Price = 79.00m,
                            Title = "Advanced UI/UX Design with Figma"
                        },
                        new
                        {
                            CourseId = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Foundational course covering Pandas, NumPy, and basic ML algorithms.",
                            Duration = 30,
                            InstructorId = 1,
                            Level = "Beginner",
                            Price = 99.00m,
                            Title = "Introduction to Data Science (Python)"
                        },
                        new
                        {
                            CourseId = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Learn SEO, content, and social media marketing techniques.",
                            Duration = 10,
                            InstructorId = 3,
                            Level = "Beginner",
                            Price = 39.99m,
                            Title = "Digital Marketing & SEO Strategies"
                        },
                        new
                        {
                            CourseId = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Comprehensive guide to vector graphics and illustration techniques.",
                            Duration = 25,
                            InstructorId = 2,
                            Level = "Intermediate",
                            Price = 55.00m,
                            Title = "Adobe Illustrator Mastery"
                        });
                });

            modelBuilder.Entity("OnlineCourses.Models.Enroll", b =>
                {
                    b.Property<int>("EnrollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrolls");

                    b.HasData(
                        new
                        {
                            EnrollId = 1,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2024, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 100,
                            StudentId = 1
                        },
                        new
                        {
                            EnrollId = 2,
                            CourseId = 2,
                            EnrolledAt = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 50,
                            StudentId = 1
                        },
                        new
                        {
                            EnrollId = 3,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 80,
                            StudentId = 2
                        },
                        new
                        {
                            EnrollId = 4,
                            CourseId = 3,
                            EnrolledAt = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 0,
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("OnlineCourses.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Certification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstructorId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            Biography = "Senior Developer and Certified Trainer.",
                            Certification = "Microsoft ASB.NET CORE MVC",
                            DateJoined = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hassan.samir@platform.com",
                            FirstName = "Hassan",
                            LastName = "Samir",
                            MiddleName = "Ali",
                            PasswordHash = "hashed_pass_inst",
                            Phone = "01012345678",
                            ProfileImage = "/images/instructor/hassan.jpg"
                        },
                        new
                        {
                            InstructorId = 2,
                            Biography = "Expert UI/UX Designer and Prototyping Specialist.",
                            Certification = "Certified Figma Designer",
                            DateJoined = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nora.mousa@platform.com",
                            FirstName = "Nora",
                            LastName = "Mousa",
                            MiddleName = "Adel",
                            PasswordHash = "hashed_nora",
                            Phone = "01198765432",
                            ProfileImage = "/images/instructor/nora.jpg"
                        },
                        new
                        {
                            InstructorId = 3,
                            Biography = "Seasoned Business Analyst and Project Manager.",
                            Certification = "PMP Certified",
                            DateJoined = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "karim.fouad@platform.com",
                            FirstName = "Karim",
                            LastName = "Fouad",
                            MiddleName = "Yasser",
                            PasswordHash = "hashed_karim",
                            Phone = "01555544433",
                            ProfileImage = "/images/instructor/karim.jpg"
                        });
                });

            modelBuilder.Entity("OnlineCourses.Models.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonId");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            LessonId = 1,
                            CourseId = 1,
                            Duration = 45,
                            OrderIndex = 1,
                            Title = "Introduction to MVC Structure"
                        },
                        new
                        {
                            LessonId = 2,
                            CourseId = 1,
                            Duration = 60,
                            OrderIndex = 2,
                            Title = "Understanding Controllers and Views"
                        },
                        new
                        {
                            LessonId = 3,
                            CourseId = 2,
                            Duration = 30,
                            OrderIndex = 1,
                            Title = "Figma Prototyping Basics"
                        },
                        new
                        {
                            LessonId = 4,
                            CourseId = 2,
                            Duration = 50,
                            OrderIndex = 2,
                            Title = "Advanced Component Creation"
                        },
                        new
                        {
                            LessonId = 5,
                            CourseId = 3,
                            Duration = 40,
                            OrderIndex = 1,
                            Title = "Setting up Python Environment"
                        },
                        new
                        {
                            LessonId = 6,
                            CourseId = 3,
                            Duration = 70,
                            OrderIndex = 2,
                            Title = "Data Cleaning with Pandas"
                        },
                        new
                        {
                            LessonId = 7,
                            CourseId = 4,
                            Duration = 55,
                            OrderIndex = 1,
                            Title = "Intro to SEO and Keyword Research"
                        },
                        new
                        {
                            LessonId = 8,
                            CourseId = 5,
                            Duration = 45,
                            OrderIndex = 1,
                            Title = "Vector Basics and Tools"
                        });
                });

            modelBuilder.Entity("OnlineCourses.Models.LessonContent", b =>
                {
                    b.Property<int>("LessonContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonContentId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonContentId");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonContents");

                    b.HasData(
                        new
                        {
                            LessonContentId = 1,
                            ContentType = "Video",
                            ContentUrl = "https://youtube.com/mvc-intro",
                            Duration = 15,
                            LessonId = 1,
                            OrderIndex = 1,
                            Title = "Module 1 Introduction Video"
                        },
                        new
                        {
                            LessonContentId = 2,
                            ContentType = "PDF",
                            ContentUrl = "/files/mvc-slides.pdf",
                            Duration = 5,
                            LessonId = 1,
                            OrderIndex = 2,
                            Title = "Setup Environment Checklist"
                        },
                        new
                        {
                            LessonContentId = 3,
                            ContentType = "Video",
                            ContentUrl = "https://vimeo.com/controllers-guide",
                            Duration = 25,
                            LessonId = 2,
                            OrderIndex = 1,
                            Title = "Deep Dive into Controllers"
                        },
                        new
                        {
                            LessonContentId = 4,
                            ContentType = "Video",
                            ContentUrl = "https://youtube.com/figma-proto",
                            Duration = 15,
                            LessonId = 3,
                            OrderIndex = 1,
                            Title = "Figma Basics Demo"
                        },
                        new
                        {
                            LessonContentId = 5,
                            ContentType = "Text",
                            ContentUrl = "/guides/python-setup.html",
                            Duration = 10,
                            LessonId = 5,
                            OrderIndex = 1,
                            Title = "Installation Guide (Text)"
                        },
                        new
                        {
                            LessonContentId = 6,
                            ContentType = "PDF",
                            ContentUrl = "https://coursematerials.com/seo-guide",
                            Duration = 20,
                            LessonId = 7,
                            OrderIndex = 1,
                            Title = "Keyword Research PDF Guide"
                        });
                });

            modelBuilder.Entity("OnlineCourses.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 49.99m,
                            CourseId = 1,
                            PaymentDate = new DateTime(2024, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Paid",
                            StudentId = 1,
                            TransactionId = "TRX1"
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 79.00m,
                            CourseId = 2,
                            PaymentDate = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Paid",
                            StudentId = 1,
                            TransactionId = "TRX2"
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 49.99m,
                            CourseId = 1,
                            PaymentDate = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Paid",
                            StudentId = 2,
                            TransactionId = "TRX3"
                        });
                });

            modelBuilder.Entity("OnlineCourses.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Comment = "Excellent course structure!",
                            CourseId = 1,
                            CreatedAt = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            StudentId = 1
                        },
                        new
                        {
                            ReviewId = 2,
                            Comment = "Very clear explanation, highly recommend.",
                            CourseId = 1,
                            CreatedAt = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            StudentId = 2
                        },
                        new
                        {
                            ReviewId = 3,
                            Comment = "Good content but needs more practical examples.",
                            CourseId = 2,
                            CreatedAt = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 3,
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("OnlineCourses.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            BirthDay = new DateTime(1998, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateJoined = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.ali@example.com",
                            FirstName = "Sara",
                            LastName = "Ali",
                            MiddleName = "Mohamed",
                            PasswordHash = "hashed_pass_std",
                            Phone = "01234567890",
                            ProfileImage = "/images/student/sara.jpg"
                        },
                        new
                        {
                            StudentId = 2,
                            BirthDay = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateJoined = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed.m@example.com",
                            FirstName = "Ahmed",
                            LastName = "Mourad",
                            MiddleName = "Khaled",
                            PasswordHash = "hashed_ahmed",
                            Phone = "01000000000",
                            ProfileImage = "/images/student/ahmed.jpg"
                        });
                });

            modelBuilder.Entity("OnlineCourses.Models.Course", b =>
                {
                    b.HasOne("OnlineCourses.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCourses.Models.Instructor", "Instructor")
                        .WithMany("CreatedCourses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("OnlineCourses.Models.Enroll", b =>
                {
                    b.HasOne("OnlineCourses.Models.Course", "Course")
                        .WithMany("Enrolls")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCourses.Models.Student", "Student")
                        .WithMany("Enrolls")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OnlineCourses.Models.Lesson", b =>
                {
                    b.HasOne("OnlineCourses.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("OnlineCourses.Models.LessonContent", b =>
                {
                    b.HasOne("OnlineCourses.Models.Lesson", "Lesson")
                        .WithMany("Contents")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("OnlineCourses.Models.Payment", b =>
                {
                    b.HasOne("OnlineCourses.Models.Course", "Course")
                        .WithMany("Payments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCourses.Models.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OnlineCourses.Models.Review", b =>
                {
                    b.HasOne("OnlineCourses.Models.Course", "Course")
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCourses.Models.Student", "Student")
                        .WithMany("Reviews")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OnlineCourses.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("OnlineCourses.Models.Course", b =>
                {
                    b.Navigation("Enrolls");

                    b.Navigation("Lessons");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("OnlineCourses.Models.Instructor", b =>
                {
                    b.Navigation("CreatedCourses");
                });

            modelBuilder.Entity("OnlineCourses.Models.Lesson", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("OnlineCourses.Models.Student", b =>
                {
                    b.Navigation("Enrolls");

                    b.Navigation("Payments");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
